export const Users = [
  {
    id: 1,
    profilePicture: "person/1.JPG",
    username: "Monk",
  },
  {
    id: 2,
    profilePicture: "person/2.JPG",
    username: "Abhi",
  },
  {
    id: 3,
    profilePicture: "person/3.PNG",
    username: "Amal Sabu",
  },
  {
    id: 4,
    profilePicture: "person/4.JPG",
    username: "Parava",
  },
  {
    id: 5,
    profilePicture: "person/5.JPG",
    username: "Jose",
  },
  {
    id: 6,
    profilePicture: "person/6.JPG",
    username: "Arnold",
  },
  {
    id: 7,
    profilePicture: "person/7.JPG",
    username: "Manu",
  },
  {
    id: 8,
    profilePicture: "person/8.PNG",
    username: "H",
  },
  {
    id: 9,
    profilePicture: "person/9.jpg",
    username: "Baby",
  },
  {
    id: 10,
    profilePicture: "person/10.jpg",
    username: "Muneer",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "post/1.PNG",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/2.JPG",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/3.JPG",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/5.JPG",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "post/9.JPG",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/10.jp g",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
